name = "rummyscoretracker"
main = "./dist/_worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rummy"
database_id = "dae39638-676b-4ac8-9d6f-b759d9b488c5"
